# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ModularGridBuilder
                                 A QGIS plugin
 This plugin creates a modular layout grid for print layouts
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-03-04
        copyright            : (C) 2024 by Alexei
        email                : modulargrid@fastmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ModularGridBuilder class from file ModularGridBuilder.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .modular_grid_builder import ModularGridBuilder
    return ModularGridBuilder(iface)
